package com.uca.entity;

public enum Description
{
    COMMUNITY_SERVICE,
    INDIVIDUAL_SERVICE,
    EXCELLENT_PARTICIPATION,
    OTHER_GOOD_CONDUCT,
    OTHER_BAD_CONDUCT,
    DUBIOUS_HYGIENE,
    LATENESS,
    MISSING_HOMEWORK
}
