package com.uca.gui;

public enum InfoMsg
{
    AJOUT_SUCCES,
    AJOUT_ECHEC,
    MODIFICATION_SUCCES,
    MODIFICATION_ECHEC,
    ID_INVALIDE,
    NOM_UTILISATEUR_EXISTE_DEJA,
    COMBINAISON_EXISTE_DEJA,
    TAILLE_MOTS_DE_PASSE_NON_RESPECTEES,
    MOT_DE_PASSE_CONFIRMATION_DIFFERENT,
    CHAMPS_NON_POSTABLES,
    ECHEC_AUTHENTIFICATION,
    AUTHENTIFICATION_NECESSAIRE,
    SESSION_TERMINEE_AUTHENTIFICATION_NECESSAIRE,
    DECONNEXION_SUCCES,
    RESSOURCE_N_EXISTE_PAS,
    PAS_D_ENSEIGNANTS_CONTACTEZ_ADMIN,
    INADEQUATE_HTTP_VERB,
    WRONG_URL__NOT_HIDDEN
}

/*
this enum could feature a 'translator'/'toString' that displays better human-readable messages
 */