package com.uca.gui;

public enum InfoMsg
{
    AJOUT_SUCCES,
    AJOUT_ECHEC,
    MODIFICATION_SUCCES,
    MODIFICATION_ECHEC,
    NOM_UTILISATEUR_DEJA_PRIS,
    CONTRAINTES_MOT_DE_PASSE_NON_RESPECTEES,
    MOT_DE_PASSE_CONFIRMATION_DIFFERENT,
    CHAMPS_VIDES_INTERDITS,
    ECHEC_AUTHENTIFICATION,
    AUTHENTIFICATION_REQUISE
}
